development:
  adapter: postgresql
  database: babushka_me_dev
  username: <%= `whoami` %>

test:
  adapter: postgresql
  database: babushka_me_test
  username: <%= `whoami` %>

production:
  adapter: postgresql
  database: babushka.me
  username: <%= `whoami` %>
