development:
  adapter: postgresql
  database: babushka_me_dev

test:
  adapter: postgresql
  database: babushka_me_test

production:
  adapter: postgresql
  database: babushka.me

next:
  adapter: postgresql
  database: next.babushka.me
